### PR TITLE
Fix #1 Accept multiple paths

### LINKED ISSUE #1: Multiple URIs
Is it possible to make live-reload watch multiple URIs? Something like [onchange](https://github.com/Qard/onchange) is doing would be great!

### PR DESCRIPTION
**Pull request by louisremi**

### CODE REVIEW

**Comment by Raynos** [comment]
lgtm.

**Comment by louisremi** [comment]
So what's the next step? : )

**Comment by Raynos** [comment]
Next step is npm publish :)

**Comment by louisremi** [comment]
exactly : )

**Comment by Raynos** [comment]
Published 1.0.0

**Comment by louisremi** [comment]
<3

**Pull request merged**
